Prevent writing failed build.php to output

diff --git a/.github/workflows/process-artisan-commands.yml b/.github/workflows/process-artisan-commands.yml
--- a/.github/workflows/process-artisan-commands.yml
+++ b/.github/workflows/process-artisan-commands.yml
@@ -89,8 +89,15 @@ jobs:
       - name: Run Generator Command
         run: |
           cd /tmp/laravel
-          cp ${{ github.workspace }}/build.php /tmp/laravel/ | php -f /tmp/laravel/build.php > /tmp/${{ matrix.laravel.v }}.x.json
-          cp /tmp/${{ matrix.laravel.v }}.x.json ${{ github.workspace }}/assets/
+          cp ${{ github.workspace }}/build.php /tmp/laravel/
+          BUILD_OUTPUT=$(php -f /tmp/laravel/build.php)
+          if [[ $? -eq 0 ]]; then
+            echo $BUILD_OUTPUT > /tmp/${{ matrix.laravel.v }}.x.json
+            cp /tmp/${{ matrix.laravel.v }}.x.json ${{ github.workspace }}/assets/
+          else
+            echo "Build failed"
+            exit 1
+          fi
 
       - name: Sync Git Changes
         run: git pull origin ${GITHUB_REF##*/} || true # can be run safely as only .x.json files are changed
